//
//  HistoryDetailViewController.swift
//  DriveRecords
//
//  Created by Hamza Khan on 06/08/2019.
//  Copyright (c) 2019 Hamza Khan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class HistoryDetailViewController: UIViewController
{
 
    var presenter : HistoryDetailViewToPresenterProtocol?
    var rideDetailRecord : RideRecord?
    
    @IBOutlet weak var lblName : UILabel!
    @IBOutlet weak var lblDistance : UILabel!
    @IBOutlet weak var lblDuration : UILabel!
    @IBOutlet weak var lblDate : UILabel!

  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    guard let record = rideDetailRecord else { return }
    presenter?.viewHasLoaded(item: record)
  }
  
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(true)
        self.title = "Detail"
    }
  
 
}
extension HistoryDetailViewController: HistoryDetailPresenterToViewProtocol{
    func setRideRecord(customerName: String, distance: String, duration: String, date: String) {
        lblDate.text = date
        lblName.text = customerName
        lblDistance.text = distance
        lblDuration.text = duration
    }
    
    
   
    
}
