//
//  HistoryDetailInteractor.swift
//  DriveRecords
//
//  Created by Hamza Khan on 06/08/2019.
//  Copyright (c) 2019 Hamza Khan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class HistoryDetailInteractor : HistoryDetailPresenterToInteractorProtocol{
    
    var presenter: HistoryDetailInteractorToPresenterProtocol?
    
    func processRideRecrod(item: RideRecord) {
        let name = item.studentName ?? ""
        let distance = Utility.formatDistanceValue(val: (item.distance ?? ""))
        let durantion = item.duration ?? ""
        let date = (item.date ?? Date()).toString()
        presenter?.didProcessRideRecord(customerName: name, distance: distance, duration: durantion, date: date)
    }
     
}



