//
//  HistoryDetailRouter.swift
//  DriveRecords
//
//  Created by Hamza Khan on 06/08/2019.
//  Copyright (c) 2019 Hamza Khan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


class HistoryDetailRouter:  HistoryDetailPresenterToRouterProtocol{
    
    static var historyDetailStoryboard : UIStoryboard{
        return UIStoryboard(name: "HistoryDetail", bundle: Bundle.main)
    }
    static func createModule(record : RideRecord)-> UIViewController{
        let view = historyDetailStoryboard.instantiateViewController(withIdentifier: "HistoryDetailViewController") as! HistoryDetailViewController
        var presenter : HistoryDetailViewToPresenterProtocol & HistoryDetailInteractorToPresenterProtocol = HistoryDetailPresenter()
        var interactor : HistoryDetailPresenterToInteractorProtocol = HistoryDetailInteractor()
        let router : HistoryDetailPresenterToRouterProtocol = HistoryDetailRouter()
        view.rideDetailRecord = record
        view.presenter = presenter
        presenter.interactor = interactor
        presenter.router = router
        presenter.view =  view
        interactor.presenter = presenter
        return view
    }
    
}
